name: Build

on:
  - push
  - pull_request

jobs:
  publish:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: [v1.15.1]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: knives/drone-rancher-redeploy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
